spring.application.name=travel-itinerary-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_planner
spring.datasource.username=postgres
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (Secret should be at least 256 bits)
jwt.secret=YOUR_JWT_SECRET
jwt.expiration=86400000


# OpenWeatherMap API
weather.api.key=YOUR_OPENWEATHER_API_KEY
weather.base.url=https://api.openweathermap.org/data/2.5
weather.geo.url=http://api.openweathermap.org/geo/1.0

# Pexels API
photo.api.key=YOUR_PEXELS_API_KEY
photo.base.url=https://api.pexels.com

# Email (SMTP) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Exchange Rate API (open.er-api.com v6)
currency.api.url=https://open.er-api.com/v6/latest
